
os: linux 

language: node.js 

services:
        - docker

before_install:
        - docker build -t dadatravisdocker -f Dockerfile.dev .

script:
        - docker run dadatravisdocker npm run test -- --coverage
